Repository JuliaGPU/Metal.jl, pull requests merged in 2023-01, with the labels that each got.

#73 Add basic SIMD shuffle up/down
  src/device/intrinsics/simd.jl
  test/device/intrinsics.jl
Labels: enhancement

#75 Optimize warp reduction for mapreduce
  src/compiler/execution.jl
  src/mapreduce.jl
Labels: performance

#67 Add documentation webpage
  .buildkite/cryptic_repo_keys/.gitignore
  .buildkite/cryptic_repo_keys/repo_key.2297e5e7
  .buildkite/pipeline.yml
  .buildkite/secure_pipeline.yml
  .buildkite/secure_pipeline.yml.signature
  .buildkite/webui.yml
  docs/.gitignore
  docs/Manifest.toml
  docs/Project.toml
  docs/deploy.jl
  docs/documenter.key.encrypted
  docs/documenter.pub
  docs/make.jl
  docs/src/api/array.md
  docs/src/api/compiler.md
  docs/src/api/essentials.md
  docs/src/api/kernel.md
  docs/src/assets/favicon.ico
  docs/src/assets/logo.png
  docs/src/faq.md
  docs/src/index.md
  docs/src/profiling.md
  src/device/intrinsics/memory.jl
  src/state.jl
Labels: documentation, help wanted

#76 Specialize GPUArrays.global_index() to improve broadcast performance
  src/gpuarrays.jl
Labels: performance
