Repository JuliaGPU/Metal.jl, pull requests merged in 2024-07, with the labels that each got.

#382 add `findall` implementation
  src/Metal.jl
  src/indexing.jl
  test/array.jl
Labels: enhancement, arrays

#384 Fix typo in docs
  docs/src/api/array.md
Labels: documentation

#394 Add erfinv
  ext/SpecialFunctionsExt.jl
  test/device/intrinsics.jl
Labels: enhancement

#395 Add expm1
  src/device/intrinsics/math.jl
  test/device/intrinsics.jl
Labels: enhancement

#392 Don't export `MTL`
  .buildkite/pipeline.yml
  LocalPreferences.toml
  Project.toml
  bin/metallib-as
  bin/metallib-load
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/api/array.md
  docs/src/api/essentials.md
  docs/src/usage/array.md
  examples/gtk.jl
  examples/unified_memory.jl
  lib/mps/MPS.jl
  lib/mps/copy.jl
  lib/mps/decomposition.jl
  lib/mps/images.jl
  lib/mps/linalg.jl
  lib/mps/matrix.jl
  lib/mps/vector.jl
  lib/mtl/MTL.jl
  lib/mtl/buffer.jl
  lib/mtl/library.jl
  lib/mtl/storage_type.jl
  src/Metal.jl
  src/array.jl
  src/broadcast.jl
  src/compiler/execution.jl
  src/memory.jl
  src/pool.jl
  src/version.jl
  test/array.jl
  test/capturing.jl
  test/device/intrinsics.jl
  test/execution.jl
  test/metal.jl
  test/mps/copy.jl
  test/mps/matrix.jl
  test/profiling.jl
  test/runtests.jl
Labels: breaking

#400 Unexport some high-level MPS functionality from `MPS`
  lib/mps/images.jl
  lib/mps/matrix.jl
Labels: breaking
